name: "Auto-assign themes to PR"

on:
  - pull_request

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
      
    runs-on: self-hosted

    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}