name: Main

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - '**/src/**'
      - '**/.github/**'
      - '**/pom.xml'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Maven Verify
        run: mvn -B clean verify

  codecov:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Test Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  sonarcloud:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

  
